### PR TITLE
Additional chains were added to Rainbow

### LINKED ISSUE #20: RainbowKit Allowed Networks
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Rainbow kit only allows some networks. 
Screen Shot 2022-09-21 at 1 33 09 AM

### Expected Behavior

RainbowKit should allow Polygon, Optimism, Arbitrum 

XMTP signing can have any EVM wallet, so we can support all of them. 

https://www.rainbowkit.com/docs/custom-chains

### Steps To Reproduce

Sign in to demo.relay.cc while Metamask is on Polygon

### PR DESCRIPTION
**Pull request by BrianS111**
Optimism
90144ECB-42F5-4719-BF44-8BCD0B5F19E6
, Polygon and Arbitrum were added to available chains. 

Closes https://github.com/relaycc/relay/issues/20

### CODE REVIEW

**Comment by BrianS111** [comment]
Also includes the new header from PR https://github.com/relaycc/receiver-example-cra/pull/3

**Review by killthebuddh4 — CHANGES_REQUESTED** [review]
Please remove the unrelated changes. At a glance it looks like the only file in this changeset should be `index.tsx`.

**Comment by killthebuddh4** [comment]
@BrianS111 Bump.

**Comment by BrianS111** [comment]
Is this a feature we still want on the Rainbow Kit CRA site or are we tossing out the idea b/c it's more of a thing users of our app will decide / adjust on their own?

**Pull request closed without merging**
