### PR TITLE
Header added with a link to GH

### PR DESCRIPTION
**Pull request by BrianS111**
PR for https://github.com/relaycc/receiver/issues/63

### CODE REVIEW

**Comment by BrianS111** [comment]
New View

7D4C7430-123E-4853-B451-324E36326CC7

**Comment by BrianS111** [comment]
Closes https://github.com/relaycc/receiver/issues/63

**Review by killthebuddh4 — CHANGES_REQUESTED** [review]
A couple minor things:
* Move the GH logo svg into `/public`
* Add the header to the `CustomExample` view

**Comment by BrianS111** [comment]
GH logo was turned into an svg file, and added to all three pages. The website was built with create react app, so It appears it wants all the images in the src directory. Everything has been completed except putting the svg in public

**Review by killthebuddh4 — APPROVED** [review]

**Pull request merged**
